DATABASE_URL = "mongodb://admin:password@mongodb:27017/healthcare?authSource=admin"
HEDERA_ACCOUNT_ID = "0.0.5800024"
HEDERA_PRIVATE_KEY = "3030020100300706052b8104000a0422042076118fe0869509b6fe82979d18e16b9838d1552ae3cfd2d97ed3bc19e674f71f"
JWT_SECRET = "this_is_a_super_secret_jwt_secret_that_is_long_enough"
IPFS_ENCRYPTION_KEY = "b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2"
GOOGLE_CLIENT_ID = "471501066001-upoq32ahhed0pj7b2b06tro9q4649gtn.apps.googleusercontent.com"
TWILIO_ACCOUNT_SID = "<your-twilio-account-sid>"
TWILIO_AUTH_TOKEN = "<your-twilio-auth-token>"
TWILIO_PHONE_NUMBER = "+1234567890" # e.g., +15017122661
GEMINI_API_KEY = "AIzaSyBBtiisbapxO2GQUVz3eRh-ou5eNsLIvjo"
HEALTHCARE_ACCESS_CONTROL_CONTRACT_ID = "0x66708FfE755085dDfb1C08A79283EbF8702196Cf"
VERIFIABLE_CREDENTIALS_CONTRACT_ID = "0x68a1c1F24ad593b13473D492de80c136AA0F190e"
AUDIT_TRAIL_CONTRACT_ID = "0xD386c806815DAC291d1F21d35e6Ca8e1e5D93313"
